name = "url-shortener"
main = "src/worker.js"
account_id = "68dca54a44bd4d964f21406a2a290007"
compatibility_date = "2025-06-25"
workers_dev = false
preview_urls = false

[observability.logs]
enabled = true

[[d1_databases]]
binding = "D1_URL_SHORTENER"
database_name = "mfc-website"
database_id = "76214d95-18a7-4a65-aa40-22415b7ce1bb"
remote = true
